apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-grafana
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: 'managed-nfs-storage'
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
