kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-data
  annotations:
    volume.beta.kubernetes.io/storage-class: 'managed-nfs-storage'
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
